name: location_tracking
description: A Flutter project for location tracking.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"  # Specify the Dart SDK constraint

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.5
  geolocator: ^10.0.1
  get: ^4.6.5
#  flutter_map: ^7.0.2

flutter:
  uses-material-design: true

# Other configurations...
